### ISSUE TITLE
Upgrader Parameters Necessary for Simulation

### ISSUE THREAD

**Issue by torresje** [pyrolysis/nrel-2fbr-docs#1]
Specs on:
- Pyrolysis vapors going into upgrader: composition, flow rate, temperature, pressure, phase
- Initial catalyst bed conditions: bed height, packing
- Upgrader geometry: location and size of all inlets and outlets

**Comment by wigging** [comment]
We also need to ask NREL about:

- Insulation and/or heat jackets around the upgrader
- Axial temperature readings, can we assume adiabatic conditions
- More information on controlling the catalyst: how does it exit the unit, when do they add new catalyst

**Comment by wigging** [comment]
Added the questions to a Word document which will be sent to NREL.
